# Generated by Django 2.1.4 on 2018-12-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
