# Generated by Django 2.1.8 on 2019-04-16 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import server.pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('sub_district', models.CharField(help_text='ตำบล', max_length=100)),
                ('district', models.CharField(help_text='อำเภอ', max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('available_on', models.DateField(blank=True, null=True)),
                ('available_off', models.DateField(blank=True, null=True)),
                ('hit_count', models.IntegerField(default=0)),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('product_price', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('product_discount_price', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('product_discount_until', models.DateField(blank=True, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_details', models.TextField(blank=True, null=True)),
                ('product_size_image', models.ImageField(null=True, upload_to=server.pages.models.upload_helper)),
                ('product_image1', models.ImageField(null=True, upload_to=server.pages.models.upload_helper)),
                ('product_image2', models.ImageField(null=True, upload_to=server.pages.models.upload_helper)),
                ('product_image3', models.ImageField(null=True, upload_to=server.pages.models.upload_helper)),
                ('product_image4', models.ImageField(null=True, upload_to=server.pages.models.upload_helper)),
                ('product_image5', models.ImageField(null=True, upload_to=server.pages.models.upload_helper)),
                ('product_image6', models.ImageField(null=True, upload_to=server.pages.models.upload_helper)),
                ('product_showcase1', models.ImageField(null=True, upload_to=server.pages.models.upload_helper)),
                ('product_showcase2', models.ImageField(null=True, upload_to=server.pages.models.upload_helper)),
                ('product_showcase3', models.ImageField(null=True, upload_to=server.pages.models.upload_helper)),
                ('product_showcase4', models.FileField(null=True, upload_to=server.pages.models.upload_helper, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-available_on'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariantDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ProductVariant')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariantOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=100)),
                ('variant_value', models.CharField(max_length=100)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page')),
            ],
        ),
        migrations.AddField(
            model_name='productvariantdetail',
            name='variant_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ProductVariantOption'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ProductVariant'),
        ),
        migrations.AddField(
            model_name='order',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariantoption',
            unique_together={('page', 'variant_name', 'variant_value')},
        ),
    ]
