# Generated by Django 2.1.8 on 2019-04-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190418_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='product_discount_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
