# Generated by Django 2.1.7 on 2019-04-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190331_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='product_size_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
