# Generated by Django 2.1.8 on 2019-04-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190425_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='updated_by',
            new_name='updater',
        ),
        migrations.AddField(
            model_name='order',
            name='order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='product_discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='page',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
