# Generated by Django 2.1.8 on 2019-04-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190404_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='product_image1',
            field=models.ImageField(null=True, upload_to='images/pages/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='product_image2',
            field=models.ImageField(null=True, upload_to='images/pages/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='product_image3',
            field=models.ImageField(null=True, upload_to='images/pages/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='product_image4',
            field=models.ImageField(null=True, upload_to='images/pages/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='product_image5',
            field=models.ImageField(null=True, upload_to='images/pages/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='product_image6',
            field=models.ImageField(null=True, upload_to='images/pages/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='product_showcase1',
            field=models.ImageField(null=True, upload_to='images/pages/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='product_showcase2',
            field=models.ImageField(null=True, upload_to='images/pages/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='product_showcase3',
            field=models.ImageField(null=True, upload_to='images/pages/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='product_showcase4',
            field=models.FileField(null=True, upload_to='videos/pages/', verbose_name=''),
        ),
    ]
