# Generated by Django 2.1.8 on 2019-04-25 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190425_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='updater',
            new_name='updated_by',
        ),
    ]
