# Generated by Django 2.1.8 on 2019-04-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20190425_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='updated_by',
            new_name='updater',
        ),
    ]
