# Generated by Django 2.1.8 on 2019-04-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20190407_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='available_off',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='available_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='product_discount_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
