# Generated by Django 2.1.8 on 2019-04-07 03:40

from django.db import migrations, models
import server.pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20190407_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='hit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='page',
            name='product_image1',
            field=models.ImageField(null=True, upload_to=server.pages.models.upload_helper),
        ),
        migrations.AlterField(
            model_name='page',
            name='product_image2',
            field=models.ImageField(null=True, upload_to=server.pages.models.upload_helper),
        ),
        migrations.AlterField(
            model_name='page',
            name='product_image3',
            field=models.ImageField(null=True, upload_to=server.pages.models.upload_helper),
        ),
        migrations.AlterField(
            model_name='page',
            name='product_image4',
            field=models.ImageField(null=True, upload_to=server.pages.models.upload_helper),
        ),
        migrations.AlterField(
            model_name='page',
            name='product_image5',
            field=models.ImageField(null=True, upload_to=server.pages.models.upload_helper),
        ),
        migrations.AlterField(
            model_name='page',
            name='product_image6',
            field=models.ImageField(null=True, upload_to=server.pages.models.upload_helper),
        ),
        migrations.AlterField(
            model_name='page',
            name='product_showcase1',
            field=models.ImageField(null=True, upload_to=server.pages.models.upload_helper),
        ),
        migrations.AlterField(
            model_name='page',
            name='product_showcase2',
            field=models.ImageField(null=True, upload_to=server.pages.models.upload_helper),
        ),
        migrations.AlterField(
            model_name='page',
            name='product_showcase3',
            field=models.ImageField(null=True, upload_to=server.pages.models.upload_helper),
        ),
        migrations.AlterField(
            model_name='page',
            name='product_showcase4',
            field=models.FileField(null=True, upload_to=server.pages.models.upload_helper, verbose_name=''),
        ),
    ]
