# Generated by Django 2.1.8 on 2019-04-29 09:16

from django.db import migrations, models
import server.pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20190425_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, default=server.pages.models.my_random_slug, max_length=20, unique=True),
        ),
    ]
