# Generated by Django 2.1.8 on 2019-04-09 08:04

from django.db import migrations, models
import server.pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20190407_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-available_on']},
        ),
        migrations.AlterField(
            model_name='page',
            name='product_size_image',
            field=models.ImageField(null=True, upload_to=server.pages.models.upload_helper),
        ),
    ]
