# Generated by Django 2.1.8 on 2019-04-16 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20190416_1122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OderItems',
            new_name='OderItem',
        ),
    ]
