# Generated by Django 2.1.8 on 2019-04-16 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20190416_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VariantOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Size, Material, Colour', max_length=200)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page')),
            ],
        ),
        migrations.CreateModel(
            name='VariantValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='S,M,XL for size option', max_length=200)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page')),
            ],
        ),
        migrations.RenameModel(
            old_name='OderItem',
            new_name='OrderItem',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariantoption',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ProductVariant'),
        ),
        migrations.AddField(
            model_name='productvariantoption',
            name='variant_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.VariantOption'),
        ),
        migrations.AddField(
            model_name='productvariantoption',
            name='variant_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.VariantValue'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariantoption',
            unique_together={('variant_option', 'variant_value')},
        ),
    ]
